// Mocks generated by Mockito 5.4.6 from annotations
// in card_hive/test/features/backup/data/repository/backup_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:card_hive/features/backup/data/bridge/backup_auth_bridge.dart'
    as _i4;
import 'package:card_hive/features/backup/domain/repositories/drive_remote_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DriveRemoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriveRemoteRepository extends _i1.Mock
    implements _i2.DriveRemoteRepository {
  MockDriveRemoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> uploadBackup(
    String? accessToken,
    String? fileName,
    List<int>? bytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadBackup, [accessToken, fileName, bytes]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<int>> downloadBackup(String? accessToken, String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#downloadBackup, [accessToken, fileId]),
            returnValue: _i3.Future<List<int>>.value(<int>[]),
          )
          as _i3.Future<List<int>>);

  @override
  _i3.Future<String?> findBackupFileId(String? accessToken, String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#findBackupFileId, [accessToken, fileName]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<DateTime?> getFileModifiedTime(
    String? accessToken,
    String? fileId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFileModifiedTime, [accessToken, fileId]),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);
}

/// A class which mocks [BackupAuthBridge].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupAuthBridge extends _i1.Mock implements _i4.BackupAuthBridge {
  MockBackupAuthBridge() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> getAccessTokenSilently() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessTokenSilently, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> interactiveSignIn() =>
      (super.noSuchMethod(
            Invocation.method(#interactiveSignIn, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
