// Mocks generated by Mockito 5.4.6 from annotations
// in card_hive/test/features/backup/domain/usecases/restore_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:card_hive/core/resources/data_state.dart' as _i2;
import 'package:card_hive/features/backup/domain/repositories/backup_repository.dart'
    as _i3;
import 'package:card_hive/features/cards/domain/entities/card_entity.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BackupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupRepository extends _i1.Mock implements _i3.BackupRepository {
  MockBackupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<void>> backup(List<_i5.CardEntity>? cards) =>
      (super.noSuchMethod(
            Invocation.method(#backup, [cards]),
            returnValue: _i4.Future<_i2.DataState<void>>.value(
              _FakeDataState_0<void>(this, Invocation.method(#backup, [cards])),
            ),
          )
          as _i4.Future<_i2.DataState<void>>);

  @override
  _i4.Future<_i2.DataState<void>> restore() =>
      (super.noSuchMethod(
            Invocation.method(#restore, []),
            returnValue: _i4.Future<_i2.DataState<void>>.value(
              _FakeDataState_0<void>(this, Invocation.method(#restore, [])),
            ),
          )
          as _i4.Future<_i2.DataState<void>>);

  @override
  _i4.Future<_i2.DataState<DateTime?>> getLastBackupTime() =>
      (super.noSuchMethod(
            Invocation.method(#getLastBackupTime, []),
            returnValue: _i4.Future<_i2.DataState<DateTime?>>.value(
              _FakeDataState_0<DateTime?>(
                this,
                Invocation.method(#getLastBackupTime, []),
              ),
            ),
          )
          as _i4.Future<_i2.DataState<DateTime?>>);
}
