// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/cards/data/models/card_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 62870931500109938),
    name: 'CardModel',
    lastPropertyId: const obx_int.IdUid(11, 8101734927521726296),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1956935281347475812),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2285761289274129723),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 5858192251813911495),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4120578690252093592),
        name: 'label',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 506706184309228241),
        name: 'number',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 260010285660874372),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2982909568387265885),
        name: 'logoPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7894219148846441729),
        name: 'note',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 731865282394944071),
        name: 'colorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1208346016047545545),
        name: 'frontPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 59566892973957703),
        name: 'backPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8101734927521726296),
        name: 'rawBarcodeSvg',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 62870931500109938),
    lastIndexId: const obx_int.IdUid(2, 260010285660874372),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [8595677417465576809],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CardModel: obx_int.EntityDefinition<CardModel>(
      model: _entities[0],
      toOneRelations: (CardModel object) => [],
      toManyRelations: (CardModel object) => {},
      getId: (CardModel object) => object.id,
      setId: (CardModel object, int id) {
        object.id = id;
      },
      objectToFB: (CardModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final labelOffset =
            object.label == null ? null : fbb.writeString(object.label!);
        final numberOffset = fbb.writeString(object.number);
        final logoPathOffset =
            object.logoPath == null ? null : fbb.writeString(object.logoPath!);
        final noteOffset =
            object.note == null ? null : fbb.writeString(object.note!);
        final frontPathOffset =
            object.frontPath == null
                ? null
                : fbb.writeString(object.frontPath!);
        final backPathOffset =
            object.backPath == null ? null : fbb.writeString(object.backPath!);
        final rawBarcodeSvgOffset =
            object.rawBarcodeSvg == null
                ? null
                : fbb.writeString(object.rawBarcodeSvg!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, labelOffset);
        fbb.addOffset(3, numberOffset);
        fbb.addOffset(4, logoPathOffset);
        fbb.addOffset(5, noteOffset);
        fbb.addInt64(6, object.colorValue);
        fbb.addOffset(8, frontPathOffset);
        fbb.addOffset(9, backPathOffset);
        fbb.addOffset(10, rawBarcodeSvgOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final numberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final colorValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final labelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final logoPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final rawBarcodeSvgParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final frontPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final backPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = CardModel(
          id: idParam,
          name: nameParam,
          number: numberParam,
          colorValue: colorValueParam,
          label: labelParam,
          logoPath: logoPathParam,
          rawBarcodeSvg: rawBarcodeSvgParam,
          frontPath: frontPathParam,
          backPath: backPathParam,
          note: noteParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CardModel] entity fields to define ObjectBox queries.
class CardModel_ {
  /// See [CardModel.id].
  static final id = obx.QueryIntegerProperty<CardModel>(
    _entities[0].properties[0],
  );

  /// See [CardModel.name].
  static final name = obx.QueryStringProperty<CardModel>(
    _entities[0].properties[1],
  );

  /// See [CardModel.label].
  static final label = obx.QueryStringProperty<CardModel>(
    _entities[0].properties[2],
  );

  /// See [CardModel.number].
  static final number = obx.QueryStringProperty<CardModel>(
    _entities[0].properties[3],
  );

  /// See [CardModel.logoPath].
  static final logoPath = obx.QueryStringProperty<CardModel>(
    _entities[0].properties[4],
  );

  /// See [CardModel.note].
  static final note = obx.QueryStringProperty<CardModel>(
    _entities[0].properties[5],
  );

  /// See [CardModel.colorValue].
  static final colorValue = obx.QueryIntegerProperty<CardModel>(
    _entities[0].properties[6],
  );

  /// See [CardModel.frontPath].
  static final frontPath = obx.QueryStringProperty<CardModel>(
    _entities[0].properties[7],
  );

  /// See [CardModel.backPath].
  static final backPath = obx.QueryStringProperty<CardModel>(
    _entities[0].properties[8],
  );

  /// See [CardModel.rawBarcodeSvg].
  static final rawBarcodeSvg = obx.QueryStringProperty<CardModel>(
    _entities[0].properties[9],
  );
}
