// Mocks generated by Mockito 5.4.6 from annotations
// in card_hive/test/features/backup/presentation/bloc/backup_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:card_hive/core/resources/data_state.dart' as _i2;
import 'package:card_hive/features/backup/data/bridge/backup_auth_bridge.dart'
    as _i3;
import 'package:card_hive/features/backup/domain/usecases/backup_usecase.dart'
    as _i5;
import 'package:card_hive/features/backup/domain/usecases/restore_usecase.dart'
    as _i7;
import 'package:card_hive/features/cards/domain/entities/card_entity.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BackupAuthBridge].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupAuthBridge extends _i1.Mock implements _i3.BackupAuthBridge {
  MockBackupAuthBridge() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String?> getAccessTokenSilently() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessTokenSilently, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> interactiveSignIn() =>
      (super.noSuchMethod(
            Invocation.method(#interactiveSignIn, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [BackupUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupUseCase extends _i1.Mock implements _i5.BackupUseCase {
  MockBackupUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<void>> call({
    required List<_i6.CardEntity>? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i4.Future<_i2.DataState<void>>.value(
              _FakeDataState_0<void>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i4.Future<_i2.DataState<void>>);
}

/// A class which mocks [RestoreUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestoreUseCase extends _i1.Mock implements _i7.RestoreUseCase {
  MockRestoreUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<void>> call({dynamic params}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i4.Future<_i2.DataState<void>>.value(
              _FakeDataState_0<void>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
          )
          as _i4.Future<_i2.DataState<void>>);
}
